#!/bin/bash

d=$(dirname "$0")
echo "slim 
arm64 -arm64" | \
while read -r a suf; do
    f="$d/Dockerfile.singularity$suf-shim"
    echo "Generating $f"

    sed -e "s,{IMAGE},quay.io/singularity/singularity:v3.9.0-$a,g" < "$d/Dockerfile.singularity-template" >| "$f"
done
