#!/bin/bash

# Dummy docker command for OSX testing.  We handle the command lines that 
# the tests use (and give the output the tests expect).

# If the script is running under BATS, FD 3 is open (for output that isn't 
# caught by BATS and passes right through to the output).  If not, we need 
# to open it.
if ! ( echo >&3 ) 2> /dev/null
then
    exec 3>&2
fi

if [ "$*" = "pull mjtravers/singularity-shim:latest" ]
then
    cat << EOF
latest: Pulling from mjtravers/singularity-shim
Digest: sha256:e906fda34b081178b0fbf89818da3509f958fcb7e6d36bd69204665fb7675d5d
Status: Image is up to date for mjtravers/singularity-shim:latest
docker.io/mjtravers/singularity-shim:latest
EOF
elif [ "$1" = "run" -a \
       "$2" = "--privileged" -a \
       "$3" = "--rm" -a \
       "$4" = "-e" -a \
       "$5" = "UID=501" -a \
       "$6" = "-e" -a \
       "$7" = "GID=20" -a \
       "$8" = "-v" -a \
       "${10}" = "-v" -a \
       "${12}" = "-v" -a \
       "${14}" = "-w" -a \
       "${16}" = "-v" -a \
       "${17}" = "/etc/localtime" -a \
       "${18}" = "mjtravers/singularity-shim:latest" -a \
       "${19}" = "exec" -a \
       "${20}" = "-c" -a \
       "${21}" = "-e" -a \
       "${22}" = "-B" -a \
       "${24}" = "-H" -a \
       "${26}" = "--pwd" -a \
       "${29}" = "/singularity" -a \
       "${30}" = "foo bar" -a \
       "${31}" = "blah" -a \
       "${32}" = "45.5" -a \
       "${33}" = "/dir" -a \
       "${34}" = "bar;" -a \
       "${35}" = "foo&" -a \
       "${36}" = "\${foo}" ]
then
    cat << EOF
arg #1=<foo bar>
arg #2=<blah>
arg #3=<45.5>
arg #4=</dir>
arg #5=<bar;>
arg #6=<foo&>
arg #7=<\${foo}>
EOF
else
    echo "$0: unhandled command line:" >&3
    i=1
    for arg in "$@"
    do
        echo "    \$${i} = <$arg>" >&3
        i=$(($i+1))
    done
    exit 1
fi

exit 0
