name: Update container images

on:
  push:
    branches: ['master']
    paths:
      - image/*/Singularity*
  workflow_dispatch:
jobs:
  build-and-push-apptainer:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    container:
      image: ghcr.io/courtois-neuromod/repronim_buildenv:master
      options: "--device=/dev/fuse --security-opt apparmor=unconfined --security-opt seccomp=unconfined --security-opt systempaths=unconfined"
    steps:
      - name: Setup git
        run: |
          git config --global user.name "GitHub al'MiGhtY"
          git config --global user.email "git@github.com"
      - name: install dataset
        run: datalad install -s https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git /work
      - name: Build new apptainer image
        run: |
          cd /work
          deffile=$(git show --name-only | grep Singularity)
          target_image=${deffile/Singularity./}.sing
          datalad run --output $target_image -m "build container ${target_image} from ${deffile}" -- apptainer build $target_image $deffile
          datalad push --to storage-remote || true
          datalad push --to origin
